config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'lists#index'
  resources :lists, except: [:edit, :update] do
  	collection do
    	get 'bookmarks'
    	get 'public'
  	end
  end
  resources :tasks, only: [:create, :destroy]
  resources :notification, only: [:index]
  resources :favorites, only: [:create, :destroy]
  get 'messaging' => 'messaging#stream', :as => 'messaging'
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :list
	validates_uniqueness_of :user_id, scope: :list_id
	validates_presence_of :user, :list


end

app/models/list.rb
class List < ActiveRecord::Base
	 belongs_to :user
	 has_many :tasks, dependent: :destroy, :inverse_of => :list
	 has_many :favorites
	 has_many :favorite_users, through: :favorites, source: :user
	 
	 paginates_per 50
	 validates_presence_of :name
	 scope :public_lists, -> (user) { where(public: true).where.not(user_id: user) }
	 scope :authorized, -> (user) { where("user_id = ? or public = ?", user, true) }
	 accepts_nested_attributes_for :tasks, :reject_if => lambda { |a| a[:text].blank? }
end

app/models/task.rb
class Task < ActiveRecord::Base
	belongs_to :list
	validates_presence_of :list, :text
	has_ancestry orphan_strategy:  :destroy
	validate :parent_same_list
	delegate :user, to: :list
	scope :by_user,  -> (user, id) {
		joins(list: :user ).where(lists: {user_id: user.id}).find(id)
	}
	def parent_same_list
		node = self.parent
		errors.add(:ancestry, "should be in the same list") if node and node.list != self.list
	end

	def nodes_to_remove
		nodes = [self]
		node = self
		while node.is_only_child? do
			node = node.parent
			node ? (nodes << node) : break
		end
		nodes
	end

	def destroy_recusive
		nodes = self.nodes_to_remove
		nodes.each do |node|
			node.destroy
		end
		nodes
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  	devise :database_authenticatable, :registerable,:recoverable, :rememberable, :trackable, :validatable

  	has_many :lists
  	has_many :favorites
	has_many :favorite_lists, through: :favorites, source: :list

	def add_favorite(list)
		Favorite.create(user: self, list: list) if can_favorite?(list)
	end

	def can_favorite?(list)
		(list.public? and list.user != self)
	end


	def favorite(list)
	 	Favorite.find_by(list_id: list.id, user_id: self.id)
	end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_favorite, only: [:destroy]

	def create
		@list = List.find favorite_params[:list_id]
		current_user.add_favorite(@list)
		respond_to do |format|
		    format.js
		end
	end

	def destroy
		@list = @favorite.list
		@favorite.destroy if @favorite.user == current_user
		respond_to do |format|
		    format.js
		end
	end

	private
	def set_favorite
		@favorite = Favorite.find params[:id]
	end

	def favorite_params
		params.require(:favorite).permit(:list_id)
	end

end

app/controllers/favorities_controller.rb
class FavoritiesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_favorite, only: [:destroy]

	def create
		@list = List.find favorite_params[:list_id]
		current_user.add_favorite(@list)
		respond_to do |format|
		    format.js
		end
	end

	def destroy
		@list = @favorite.list
		@favorite.destroy if @favorite.user == current_user
		respond_to do |format|
		    format.js
		end
	end

	private
	def set_favorite
		@favorite = Favorite.find params[:id]
	end

	def favorite_params
		params.require(:favorite).permit(:list_id)
	end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_list, only: [:show,  :destroy]
	responders :location, :flash
  	respond_to :html

	def index
		@list = List.new
		index_lists
	end

	def bookmarks
		@lists = current_user.favorite_lists.page(params[:page])
	end

	def public
		@lists = List.public_lists(current_user).page(params[:page])
	end

	def show
		@task = Task.new
		@task.list_id = @list.id
		@tasks = @list.tasks.page(params[:page])
	end

	def create
		@list = List.create(list_params.merge(user: current_user))
		respond_with @list do |format|
			unless @list.valid?
				index_lists
		    	format.html { render "index" }
			end
		end
	end

	def destroy
		@list.destroy
		respond_with @list
	end

	private

	def index_lists
		@lists = current_user.lists.page(params[:page])
		@list.tasks.build
	end

    def set_list
      @list = List.authorized(current_user).find(params[:id])
    end

     def list_params 
      params.require(:list).permit(:name, :public,  tasks_attributes: :text )
    end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action :authenticate_user!
	before_action :set_task, only: [:destroy]
	responders :location, :flash
  	respond_to :html

	def create
		@list = current_user.lists.find task_params[:list_id]
		@task = @list.tasks.create task_params
		respond_with @task, location: -> { list_path(@task.list) } do |format|
			unless @task.valid?
				@tasks = @list.tasks
		    	format.html { render "lists/show" }
			end
		end
	end

	def destroy
		@task.destroy_recusive
		respond_with @task, location: list_path(@task.list)
	end

	private
    def set_task
    	@task = Task.by_user(current_user, params[:id])
    end

    def task_params
      params.require(:task).permit(:text, :parent_id, :list_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association)
    	new_object = f.object.send(association).klass.new
    	id = new_object.object_id
    	fields = f.fields_for(association, new_object, child_index: id) do |builder|
      		builder.input :text, required: false
    	end
    	link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end


  	def nested_messages(messages)
      nested = messages.map do |message, sub_messages|
        render(message) + content_tag(:div, nested_messages(sub_messages), :class => "nested_messages")
      end
      nested.join.html_safe
	end

end

app/helpers/favorites_helper.rb
module FavoritesHelper

	def bookmark(list, user = current_user)
		if user.can_favorite? list
			user.favorite(list) ? remove_button(list) : add_button(list)
		end
	end

	def remove_button(list, user = current_user)
		link_to 'Remove Bookmark', favorite_path(user.favorite(list)), 
				:confirm => 'Are you sure?', :method => :delete, :remote => true, class: "remove-bookmark btn btn-default"
	end

	def add_button(list)
		render(partial: "favorites/form", locals: {list: list})
	end
end

app/helpers/favorities_helper.rb
module FavoritiesHelper

	def bookmark(list, user = current_user)
		if user.can_favorite? list
			user.favorite(list) ? remove_button(list) : add_button(list)
		end
	end

	def remove_button(list, user = current_user)
		link_to 'Remove Bookmark', favority_path(user.favorite(list)), 
				:confirm => 'Are you sure?', :method => :delete, :remote => true, class: "remove-bookmark btn btn-default"
	end

	def add_button(list)
		render(partial: "favorities/form", locals: {list: list})
	end
end

app/helpers/lists_helper.rb
module ListsHelper
	def remove_list(list, user = current_user)
		link_to 'Remove', list_path(list), :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger" if list.user == user
	end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/favorites/_form.html.erb
<%= simple_form_for(Favorite.new, url:  favorites_path, remote: true, html: { class: "add-bookmark"} ) do |f| %>
	<%= f.hidden_field :list_id, value: list.id %>
	<%= f.button :submit, 'Add Bookmark' %>
<% end %>

app/views/favorites/create.js.erb
$("#list-id-<%= @list.id %> .add-bookmark").replaceWith('<%= escape_javascript remove_button(@list) %>');

app/views/favorites/destroy.js.erb
$("#list-id-<%= @list.id %> .remove-bookmark").replaceWith('<%= escape_javascript add_button(@list) %>');

app/views/layouts/_header_no_user.html.erb
<ul class="nav navbar-nav">
	<li><%= link_to "Sign-in", new_user_session_path %></li>
	<li><%= link_to "Sign-up", new_user_registration_path %></li>
</ul>

app/views/layouts/_header_user.html.erb
<ul class="nav navbar-nav">
	<li><%= link_to "My lists", lists_path %></li>
	<li><%= link_to "Public Lists", public_lists_path %></li>
	<li><%= link_to "Bookmark Lists", bookmarks_lists_path %></li>
	<li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Dtasks</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-default" role="navigation">
		 	<div class="container-fluid">
			    <div class="navbar-header">
			      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
			        <span class="sr-only">Toggle navigation</span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			        <span class="icon-bar"></span>
			      </button>
			      <%= link_to "DTasks", root_path, class: "navbar-brand" %>
			    </div>

			    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			    	<% if current_user %>
			    		<%= render :partial => 'layouts/header_user' %>
			    	<% else  %>
			    		<%= render :partial => 'layouts/header_no_user' %>
			      	<% end %>
			    </div>
		  	</div>
		</nav>
		<p><%= flash[:alert] %></p>
		<p><%= flash[:notice] %></p>
		<div class="container-fluid">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list, url: lists_path,   html: { class: 'form-inline' },) do |f| %>
  <%= f.error_notification %>
  <%= f.input :name, required: false, autofocus: true %>
  <%= f.input :public, as: :boolean%>
  <%= link_to_add_fields "Task add", f, :tasks %>
  <%= f.button :submit %>
<% end %>

app/views/lists/_list.html.erb
<div class="alert alert-warning" id="list-id-<%= list.id %>">
	<%= link_to list_path(list) do %>
		<h3><%= list.name %></h3>
		<small><%= time_ago_in_words list.created_at %> ago</small>
	<% end %>
	<%= remove_list(list) %>
	<%= bookmark(list) %>
</div>

app/views/lists/bookmarks.html.erb
<h1>BookMark Lists</h1>
<div class="lists">
	<%= render(partial: "list", collection: @lists) || "You don't have any Bookmark list" %>
</div>

app/views/lists/index.html.erb
<%= render "form" %>
<h1>My Lists</h1>
<div class="lists">
	<%= render(partial: "list", collection: @lists) || "You don't have any list" %>
</div>

app/views/lists/public.html.erb
<h1>Public Lists</h1>
<div class="lists">
	<%= render(partial: "list", collection: @lists) || "Don't have any public list" %>
</div>

app/views/lists/show.html.erb
<h2><%= @list.name %></h2>
<%= nested_messages(@tasks.arrange(:order => :created_at)) || "You don't have any task" %>
<% if current_user == @list.user %>
	<%= render(partial: "tasks/form", locals: { parent_id: nil, list_id: @list.id, task: @task })  %>
<% end %>

app/views/tasks/_form.html.erb
<%= simple_form_for(task, url: tasks_path ) do |f| %>
	<%= f.error_notification %>
	<% if parent_id %>
		<%= f.hidden_field :parent_id, value: parent_id %>
	<% end %>
	<%= f.hidden_field :list_id, value: list_id %>
	<%= f.input :text, value: '' %>
	<%= f.button :submit %>
<% end %>

app/views/tasks/_task.html.erb
<div class="alert alert-warning" id="task_id_<%=task.id%>">
	<p><%= task.text %></p>
	<small><%= time_ago_in_words task.created_at %> ago</small>
	<% if task.user == current_user %>
		<a href="#" class="reply btn btn-success">Sub-Tasks</a>
		<div class="reply_form reply_task_id_<%=task.id%>">
			<%= render(partial: "tasks/form", locals: { parent_id: task.id, list_id: task.list_id, task: Task.new })  %>
		</div>
		<%= link_to 'Done', task_path(task), :confirm => 'Are you sure?', :method => :delete, class: "btn btn-danger" %>
	<% end %>
</div>